### ISSUE TITLE
Update for production deployment?

### ISSUE THREAD

**Issue by dmendis** [zen-js-code/react-universal-web-apps#6]
Is it possible to update the samples to produce a production build as well? 

Right now the app is hooked up to produce a app.js for the react parts. These can be easily shifted to produce a minified version. However, the sample is using `node-dev` and `babel-register` (which I read isn't recommended to run in prod) to run up the server. Can this be put together in gulp with webpack and babel?

I am new to the node world in general. Any help would be appreciated.

**Comment by dnutels** [comment]
Hey.

This was, as you probably know, an example illustrating an article, so I didn't plan to do any support.

In general, however, you can:
1. replace node-dev with node
2. build your server with webpack + babel, instead of babel-register; no need for gulp
3. pass -p as an option to webpack build to issue a production build
